version: '3.7'

services:
  db:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pg_queue_poc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./test/scripts:/docker-entrypoint-initdb.d
  test:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - "db:database"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - node_modules:/app/node_modules

volumes:
  node_modules:
